Added some stuff to the gitignore
ZomoXYZ/Discord-Bot-Client pull request #21
Opened 2020-03-15 18:46 UTC by Sulfrix

This stuff should've already been in gitignore.

2020-07-20 22:29 UTC, AL1L commented on .gitignore
> +package-lock.json
As said by @SwanX1 this shouldn't be here

2020-10-11 15:26 UTC, BRAVO68WEB approved these changes

2020-12-13 07:34 UTC, AL1L requested changes

2020-12-13 07:34 UTC, AL1L commented on .gitignore
> +package-lock.json
Don't add lock files to gitignore

2021-03-03 20:04 UTC, merged

2021-03-24 16:20 UTC, AL1L commented
@ZomoXYZ little late, but why did you merge this? Lock files are not supposed to be ignored.